---
- name: Add minio repository
  shell: helm repo add minio https://helm.min.io/

- name: Add bitnami repository
  shell: helm repo add bitnami https://charts.bitnami.com/bitnami

- name: Download subcharts into infrastructure directory
  shell: helm dep up ../infrastructure

- name: Installing infrastructure chart
  shell: "helm install infrastructure ../infrastructure -n infrastructure --create-namespace --atomic --wait-for-jobs --timeout=300s" 

- name: Deploying Ingress rules to infrastructure namespace  
  shell: "kubectl apply -f ../ingress-nginx/ingress-rules-infrastructure.yaml"   
...