---
- name: Add bitnami repository
  shell: helm repo add bitnami https://charts.bitnami.com/bitnami     

- name: Download subcharts into keycloak instance directory
  shell: helm dep up keycloak-instance
...