---
- name: Add minio repository
  shell: helm repo add minio https://helm.min.io/

- name: Add bitnami repository
  shell: helm repo add bitnami https://charts.bitnami.com/bitnami     

- name: Download subcharts into infrastructure directory
  shell: helm dep up infrastructure
...