---
- name: Deploying keycloak-proxy chart  
  block:
    - name:  Deploying keycloak-proxy chart
      shell: "helm upgrade --install keycloak-proxy ../keycloak-proxy -n {{ namespace }} --create-namespace" 
  rescue:
    - name: Abort ongoing upgrade/rollback/install
      shell: | 
        kubectl -n {{ namespace }} delete secret -l name=keycloak-proxy,status=pending-upgrade --ignore-not-found=true
        kubectl -n {{ namespace }} delete secret -l name=keycloak-proxy,status=pending-rollback --ignore-not-found=true
        kubectl -n {{ namespace }} delete secret -l name=keycloak-proxy,status=pending-install --ignore-not-found=true

    - name: Installing keycloak-proxy chart
      shell: "helm upgrade --install keycloak-proxy ../keycloak-proxy -n {{ namespace }} --create-namespace"   
  always:      
    - name: Waiting for keycloak-proxy deployment
      block:
        - name: Wait until all keycloak-proxy pods running
          shell: "kubectl get pods -o json -n {{ namespace }} --selector release=keycloak-proxy"
          register: kubectl_get_pods
          until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
          retries: 30
          delay: 20
          no_log: true   
  
        - name: Waiting for keycloak-proxy-config-init job completion
          shell: "kubectl wait --namespace={{ namespace }} --for=condition=complete job/keycloak-proxy-config-init --timeout=300s"    

        - name: Waiting untill all keycloak-proxy pods are ready
          shell: "kubectl wait --namespace={{ namespace }} --for=condition=Ready pods --selector release=keycloak-proxy --timeout=300s" 

        - name: Deploying proxy Ingress rule to momentum namespace  
          shell: "kubectl apply -f ../ingress-nginx/ingress-rule-proxy.yaml"

        - meta: end_host  
      rescue:
        - name: Rolling back failed keycloak-proxy release
          shell: "helm rollback keycloak-proxy -n {{ namespace }}"
            
        - name: Stop deployment
          shell: /bin/false
...

