---
- name: Add prometheus-community repository
  shell: helm repo add linkerd https://prometheus-community.github.io/helm-charts   

- name: Download subcharts into monitoring directory
  shell: helm dep up ../monitoring

- name:  Deploying monitoring chart
  shell: "helm upgrade --install monitoring ../monitoring -n monitoring --atomic --wait-for-jobs --create-namespace" 
...
