
- name: Deploying client chart  
  block:
    - name:  Deploying client chart
      shell: "helm upgrade --install client ../client -n {{ namespace }} --create-namespace " 
  rescue:
    - name: Abort ongoing upgrade/rollback/install
      shell: | 
        kubectl -n {{ namespace }} delete secret -l name=client,status=pending-upgrade --ignore-not-found=true
        kubectl -n {{ namespace }} delete secret -l name=client,status=pending-rollback --ignore-not-found=true
        kubectl -n {{ namespace }} delete secret -l name=client,status=pending-install --ignore-not-found=true

    - name: Installing client chart
      shell: "helm upgrade --install client ../client -n {{ namespace }} --create-namespace" 
  always:
    - name: Checking deployment success
      block:
        - name: Wait until all client pods are running
          shell: "kubectl get pods -o json -n {{ namespace }} --selector release=client"
          register: kubectl_get_pods
          until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
          retries: 30
          delay: 10
          no_log: true 

        - name: Waiting untill all client pods are ready
          shell: "kubectl wait --namespace={{ namespace }} --for=condition=Ready pods --selector release=client --timeout=420s"   

        - name: Waiting for clientinitconfig job completion
          shell: "kubectl wait --namespace={{ namespace }} --for=condition=complete job/initclientconfig --timeout=120s"   

        - name: Waiting for userservice-init-config job completion
          shell: "kubectl wait --namespace={{ namespace }} --for=condition=complete job/userservice-init-config --timeout=120s"     

        - name: Restarting api pods for config reload
          shell: "kubectl rollout restart deployment api -n {{ namespace }}"

        - meta: end_host
      rescue:
        - name: Rolling back failed client release
          shell: "helm rollback client -n {{ namespace }}"
            
        - name: Stop deployment
          shell: /bin/false
...