---
- name: Addding certificate-manager helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io" 

- name: Deploying cert-manager chart
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    atomic: true
    values:
      installCRDs: true

- name: Deploying certificate clusterissuer configuration
  shell: "kubectl apply -f ../cert-manager/certman-clusterissuer.yaml"      
...
